language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t learn3184/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true learn3184/react-test npm test
  
after_success:
  - docker build -t learn3184/multi-client ./client
  - docker build -t learn3184/multi-nginx ./nginx
  - docker build -t learn3184/multi-server ./server
  - docker build -t learn3184/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push learn3184/multi-client
  - docker push learn3184/multi-nginx
  - docker push learn3184/multi-server
  - docker push learn3184/multi-worker